export type Bursary = {
  id: string
  name: string
  provider: string
  category: string
  studyLevel: string
  fundingType: string
  province: string
  minimumMark: number
  closes: string
  daysLeft: number
  match: number
  coverage: string[]
  eligibility: string[]
  documents: string[]
  description: string
}

export const bursaries: Bursary[] = [
  { id: 'engineering-future', name: 'Engineering Future Leaders Bursary', provider: 'Ubuntu Skills Foundation', category: 'Engineering', studyLevel: 'Undergraduate', fundingType: 'Full funding', province: 'National', minimumMark: 65, closes: '30 September 2026', daysLeft: 12, match: 92, coverage: ['Tuition fees', 'Accommodation', 'Books', 'Meals', 'Transport'], eligibility: ['South African citizens', 'Undergraduate engineering students', 'Minimum academic average of 65%', 'Demonstrated financial need'], documents: ['Certified ID copy', 'Academic transcript', 'Proof of registration', 'Proof of income', 'Motivational letter'], description: 'Supports promising engineering students who want to build practical solutions for South African communities.' },
  { id: 'future-scientists', name: 'Future Scientists Fund', provider: 'Mzanzi Research Trust', category: 'Science', studyLevel: 'Undergraduate', fundingType: 'Full funding', province: 'National', minimumMark: 70, closes: '8 October 2026', daysLeft: 20, match: 88, coverage: ['Tuition fees', 'Books', 'Research costs'], eligibility: ['South African citizens', 'Studying a natural science', 'Minimum academic average of 70%'], documents: ['Certified ID copy', 'Academic transcript', 'Proof of registration', 'Motivational letter'], description: 'Funding for curious students pursuing degrees in the natural and physical sciences.' },
  { id: 'digital-pioneers', name: 'Digital Pioneers Scholarship', provider: 'Ikamva Technology Collective', category: 'IT & Computer Science', studyLevel: 'Undergraduate', fundingType: 'Full funding', province: 'Gauteng', minimumMark: 65, closes: '24 September 2026', daysLeft: 6, match: 86, coverage: ['Tuition fees', 'Laptop', 'Books', 'Mentorship'], eligibility: ['South African citizens', 'Accepted into an IT-related programme', 'Minimum academic average of 65%'], documents: ['Certified ID copy', 'Academic transcript', 'Proof of acceptance', 'Proof of income', 'CV'], description: 'Helps emerging technologists access study funding, equipment and industry mentorship.' },
  { id: 'health-horizons', name: 'Health Horizons Bursary', provider: 'Sisonke Health Initiative', category: 'Medicine & Health', studyLevel: 'Undergraduate', fundingType: 'Partial funding', province: 'KwaZulu-Natal', minimumMark: 70, closes: '15 October 2026', daysLeft: 27, match: 79, coverage: ['Tuition fees', 'Books'], eligibility: ['South African citizens', 'Health sciences students', 'Preference for KwaZulu-Natal applicants'], documents: ['Certified ID copy', 'Academic transcript', 'Proof of registration', 'Motivational letter'], description: 'Assists health sciences students committed to improving access to care.' },
  { id: 'teachers-tomorrow', name: 'Teachers of Tomorrow Award', provider: 'Bright Classrooms Network', category: 'Education', studyLevel: 'Undergraduate', fundingType: 'Full funding', province: 'Eastern Cape', minimumMark: 60, closes: '2 October 2026', daysLeft: 14, match: 76, coverage: ['Tuition fees', 'Accommodation', 'Books'], eligibility: ['BEd students', 'Minimum academic average of 60%', 'Interest in teaching in under-resourced schools'], documents: ['Certified ID copy', 'Academic transcript', 'Proof of registration', 'Motivational letter'], description: 'Develops the next generation of committed teachers for South African classrooms.' },
  { id: 'agrigrowth', name: 'AgriGrowth Student Bursary', provider: 'Harvest Futures Trust', category: 'Agriculture', studyLevel: 'Undergraduate', fundingType: 'Full funding', province: 'Free State', minimumMark: 60, closes: '31 October 2026', daysLeft: 43, match: 74, coverage: ['Tuition fees', 'Accommodation', 'Field equipment'], eligibility: ['Agriculture students', 'Minimum academic average of 60%', 'Financial need'], documents: ['Certified ID copy', 'Academic transcript', 'Proof of income', 'Motivational letter'], description: 'Supports future agricultural specialists focused on food security and sustainable farming.' },
  { id: 'finance-forward', name: 'Finance Forward Programme', provider: 'Imbokodo Finance Academy', category: 'Accounting & Finance', studyLevel: 'Undergraduate', fundingType: 'Partial funding', province: 'Western Cape', minimumMark: 68, closes: '10 October 2026', daysLeft: 22, match: 72, coverage: ['Tuition fees', 'Books', 'Mentorship'], eligibility: ['Accounting or finance students', 'Minimum academic average of 68%'], documents: ['Certified ID copy', 'Academic transcript', 'CV', 'Motivational letter'], description: 'Combines study support with mentoring for aspiring finance professionals.' },
  { id: 'law-access', name: 'Access to Justice Bursary', provider: 'Thuthukani Legal Trust', category: 'Law', studyLevel: 'Undergraduate', fundingType: 'Partial funding', province: 'National', minimumMark: 65, closes: '20 October 2026', daysLeft: 32, match: 69, coverage: ['Tuition fees', 'Books'], eligibility: ['LLB students', 'South African citizens', 'Minimum academic average of 65%'], documents: ['Certified ID copy', 'Academic transcript', 'Proof of registration', 'Proof of income'], description: 'Encourages law students interested in access to justice and community service.' },
  { id: 'tvet-trades', name: 'Skilled Trades Opportunity Fund', provider: 'BuildSA Learning Alliance', category: 'TVET', studyLevel: 'TVET College', fundingType: 'Full funding', province: 'National', minimumMark: 55, closes: '5 November 2026', daysLeft: 48, match: 66, coverage: ['Tuition fees', 'Tools', 'Transport'], eligibility: ['Registered TVET students', 'Engineering or construction trade programme'], documents: ['Certified ID copy', 'Latest results', 'Proof of registration', 'Proof of income'], description: 'Practical funding for students developing critical artisan and technical skills.' },
  { id: 'business-builders', name: 'Young Business Builders Bursary', provider: 'Vuka Enterprise Circle', category: 'Business', studyLevel: 'Undergraduate', fundingType: 'Partial funding', province: 'Gauteng', minimumMark: 60, closes: '18 October 2026', daysLeft: 30, match: 64, coverage: ['Tuition fees', 'Mentorship'], eligibility: ['Business or entrepreneurship students', 'Minimum academic average of 60%'], documents: ['Certified ID copy', 'Academic transcript', 'CV', 'Motivational letter'], description: 'Supports students with an interest in entrepreneurship and inclusive business growth.' },
  { id: 'built-environment', name: 'Built Environment Changemakers', provider: 'Cities for Tomorrow Foundation', category: 'Built Environment', studyLevel: 'Postgraduate', fundingType: 'Full funding', province: 'National', minimumMark: 70, closes: '12 November 2026', daysLeft: 55, match: 61, coverage: ['Tuition fees', 'Research costs', 'Accommodation'], eligibility: ['Honours or masters students', 'Built environment discipline', 'Minimum academic average of 70%'], documents: ['Certified ID copy', 'Academic transcript', 'Research proposal', 'CV'], description: 'Funding research that contributes to safer and more inclusive South African cities.' },
  { id: 'humanities-voices', name: 'New Voices Humanities Award', provider: 'Open Stories Foundation', category: 'Humanities', studyLevel: 'Undergraduate', fundingType: 'Partial funding', province: 'National', minimumMark: 60, closes: '28 October 2026', daysLeft: 40, match: 58, coverage: ['Tuition fees', 'Books'], eligibility: ['Humanities students', 'Minimum academic average of 60%', 'Demonstrated financial need'], documents: ['Certified ID copy', 'Academic transcript', 'Proof of income', 'Motivational letter'], description: 'Creates opportunities for students in languages, history, philosophy and social sciences.' },
]

export const categories = ['All', 'Engineering', 'Medicine & Health', 'IT & Computer Science', 'Business', 'Education', 'Law', 'Science', 'Agriculture', 'Accounting & Finance', 'Humanities', 'TVET', 'Built Environment']

export const guides = [
  { slug: 'motivation', title: 'How to write a bursary motivation', time: '4 min read', summary: 'Tell a clear, honest story about your goals, effort and the difference funding would make.', body: ['Start with your study goal and why it matters to you.', 'Use one or two specific examples that show your commitment.', 'Explain your financial circumstances honestly and respectfully.', 'Connect your goals to the provider’s purpose, then proofread before submitting.'] },
  { slug: 'documents', title: 'How to prepare your documents', time: '3 min read', summary: 'Build one organised folder so every application is easier.', body: ['Use clear file names that include your name and document type.', 'Check whether copies must be certified and how recent they must be.', 'Scan every page clearly and confirm that nothing is cut off.', 'Keep originals safe and update your folder when new results arrive.'] },
  { slug: 'deadlines', title: 'How to avoid missing deadlines', time: '3 min read', summary: 'Turn one big deadline into a few small, manageable steps.', body: ['Record the official closing date as soon as you find an opportunity.', 'Set reminders one week and three days before closing.', 'Aim to submit at least two days early.', 'Keep proof of submission and check your email regularly.'] },
  { slug: 'financial-need', title: 'What does “financial need” mean?', time: '4 min read', summary: 'Understand what providers may ask for and why.', body: ['Financial need describes whether your household can reasonably afford study costs.', 'Providers may ask for payslips, grant letters or affidavits.', 'Requirements differ, so always use the official checklist.', 'Share sensitive information only through the provider’s official application channel.'] },
  { slug: 'legitimate', title: 'How to check whether a bursary is legitimate', time: '5 min read', summary: 'Simple checks can protect your money and personal information.', body: ['Find the opportunity on the provider’s official website.', 'Never pay merely to access a bursary application.', 'Be cautious when asked for passwords, PINs or banking login details.', 'Contact the provider through independently verified contact details when uncertain.'] },
  { slug: 'interview', title: 'How to prepare for a bursary interview', time: '5 min read', summary: 'Prepare your story, examples and questions with confidence.', body: ['Research the provider and understand what they support.', 'Practise explaining your study goals in your own words.', 'Prepare examples of resilience, leadership and teamwork.', 'Join early, dress neatly and ask one thoughtful question.'] },
]